version: '3.7'

services:
  web:
    build: ./core
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core/:/usr/src/core/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user1
      - POSTGRES_PASSWORD=passwd
      - POSTGRES_DB=image_db

volumes:
  postgres_data: