# Generated by Django 3.2.3 on 2021-05-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ThumbnailSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.IntegerField(default=200)),
            ],
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=125)),
                ("presence_a_link_to_org_img", models.BooleanField(default=False)),
                (
                    "ability_to_generate_expiring_links",
                    models.BooleanField(default=False),
                ),
                ("thumbnail_sizes", models.ManyToManyField(to="plans.ThumbnailSize")),
            ],
        ),
    ]
