# Generated by Django 3.2.3 on 2021-05-30 15:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2021, 5, 30, 15, 44, 36, 421934, tzinfo=utc)
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
